services:
  web:
    # image: my_image
    build:
      context: ./me_website_project
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      # test: ["CMD", "curl", "--fail", "-H", "X-Health-Check-Secret: $${HEALTH_CHECK_SECRET}", "http://localhost:8000/health/"]
      test: [
        "CMD", "wget", "--spider", "--header", "X-Health-Check-Secret: $${HEALTH_CHECK_SECRET}",
        "http://localhost:8000/health/"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

volumes:
  static_volume:

networks:
  app_network: