# Generated by Django 5.1.6 on 2025-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
